parameters:

services:
#    app_blog.example:
#        class: App\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    api.commentManager:
        class: App\BlogBundle\Services\CommentManager
        arguments: [@doctrine.orm.entity_manager]